import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "./components/Header";

import { clearCart, getCart } from "@/api/cart";
import StoreProvider from "./jotaiStore/StoreProvider";
// import { CartContextProvider } from "./context/CartContext";
// import StoreProvider from "./store/StoreProvider";
// import { CartProvider } from "./context/CartProviderForZustand";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const cart = await getCart();

  const clearCartAction = async () => {
    "use server";
    return await clearCart();
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <CartContextProvider cart={cart}> */} {/* context api */}
        {/* <StoreProvider cart={cart}> redux */}
        {/* <CartProvider cart={cart}>  */}
        <StoreProvider>
          <Header cart={cart} clearCartAction={clearCartAction} />
          <main className="mx-auto max-w-3xl">{children}</main>
        {/* </CartProvider> */}
         {/* </StoreProvider> */}
        {/* </CartContextProvider> */}
        </StoreProvider>
      </body>
    </html>
  );
}
